### ISSUE TITLE
See what Mapzen is up to with Valhalla

### ISSUE THREAD

**Issue by stevevance** [ifed3/PBR#12]
Mapzen has made [Valhalla](https://mapzen.com/projects/valhalla), a routing service based on OSRM (like PBR). They allow the user to [change some options](https://github.com/valhalla/demos/blob/master/docs/valhalla_service.md) for all modes but bicycling!

Why are they building this?
What road blocks have they run into?
Why is bicycling the only one without options?
Will they accept contributions and ideas from the PBR team?

**Comment by stevevance** [comment]
I'm not sure anymore if Valhalla is based on OSRM; [this blog post](https://mapzen.com/blog/osrm-sunset) from Mapzen makes it seem like they built it in house.

**Comment by easherma** [comment]
I know a couple people at Mapzen; they are a friendly bunch! Perhaps we could raise the lack of cycling options as an issue on their repo?

P.S: This is their presentation from OSM: https://www.youtube.com/watch?v=hwglqOV6I9M

**Comment by stevevance** [comment]
It seems that Valhalla is doing what we want, with "[dynamic, real time costing](https://mapzen.com/blog/valhalla-bicycle-routing-options)", which means that they're applying user parameters (preferences) that affect the route outcome. 

They're allowing the user to change these parameters:
- bicycle_type = road, hybrid/city, cross, mountain - this will affect the tolerance of what kinds of path surfaces it will route you on (mountain will route you over any surface type), and your assumed speed
- cycling_speed = integer, in kilometers (this will overwrite bicycle_type)
- use_roads = decimal between 0 and 1, "indicating an increasing tolerance for riding with vehicle traffic...By specifying a value closer to 0, though, your query shows a preference for designated bicycle paths, when available" (this will overwrite bicycle_type). 

If you don't set the bicycle costing options "the route is tuned for road bicycles and the kinds of roads they can access, with a slight preference for using cycleways or roads with bicycle lanes". 

I still want to know how they weight different "cycleway=*" tags in OpenStreetMap (from worst to best: shared_lane, lane, buffered_lane, track).

**Comment by dnesbitt61** [comment]
We separate different tags into 3 classes of CycleLane: Shared (shared use with bus for instance), Dedicated (lane dedicated to bicycles), and Separated (a dedicated lane separated from vehicle traffic). We favor them in that order. Also, cycleway is a dedicated bicycle path that we favor even more. We also favor walkways that allow bicycles (but not so much if cyclist prefers using roads). You can email us at valhalla@mapzen.com if you want more details. Code for the costing can be found: https://github.com/valhalla/sif/blob/master/src/sif/bicyclecost.cc

**Comment by stevevance** [comment]
@dnesbitt61 Thanks for chiming in! Do you have plans to add other real-time costing parameters?

**Comment by dnesbitt61** [comment]
Hilliness factors are coming soon - to try to avoid hillier routes.

**Comment by stevevance** [comment]
One of the things we want to do is avoid street closures, due to resurfacing, festivals, block parties, and other construction projects. The City of Chicago provides a webpage (updated daily) for this that @strangerloops has turned into a [JSON feed](http://streetscrape.herokuapp.com/closures). 

@strangerloops is also developing an iOS app that captures street bumpiness.

**Comment by dnesbitt61** [comment]
Ah, real-time as in constantly updated. We currently are only ingesting OSM data for routing though we do hope to do some investigation into open traffic data and perhaps ways to inject closures. One needs to first associate the data to OSM ways (or portions of ways) and/or to Valhalla edges. We have not started to design this yet.
