### ISSUE TITLE
Install OSRM 

### ISSUE THREAD

**Issue by thcrock** [ifed3/PBR#2]
Keeping track of progress here:

https://github.com/ifed3/PBR/wiki/Server-Setup

**Comment by thcrock** [comment]
Done for now. OSRM is running in a screen session on the EC2 box, you can query it on the instance at localhost:5000, ie:

curl 'http://localhost:5000/viaroute?loc=41.922934,-87.696961&loc=41.884232,-87.631709&instructions=true'

**Comment by thcrock** [comment]
Per the discussions tonight, I have some new tasks going forward:
1. Provide external access to the OSRM instance
2. Daemonize OSRM
3. Write script to pull our repo, symlink the profile to our OSRM directory, rebuild the OSRM graph, and restart the daemon

This is a good resource for 1 and 2: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04

**Comment by ifed3** [comment]
Hey Tristan, can we subdivide the listed issues into their individual threads, so we can have better control over it in assigning people to it and closing the issue when finally complete

**Comment by thcrock** [comment]
Created #8 and #9, so I'm closing this.
